### ISSUE TITLE
Zaprojektować design wyszukiwarki naukowców

### ISSUE THREAD

**Issue by Nixx-K** [IO-Lab2/Front-end#1]
Filtry mają być takie, jak na grafice przesłanej w moim raporcie (dostępnym w Plikach na Teams). Chciałabym mieć obok filtrów licznik pasujących profili, który będzie aktualizowany (czyli jeżeli zawęzimy wybór np. do naukowców ze współczynnikiem IF > x), licznik profili ma się zmniejszyć do tych, które spełniają nowe wymogi filtrowania. 

Do 14.11 poproszę o informację na temat tego, co dotychczas uda Wam się zrobić.

**Comment by ikmmm** [comment]
[Wstępny projekt UI strony głównej, menu wyboru instytutów i menu filtrów](https://github.com/user-attachments/files/17740870/BazaWiedzy_Menu_v1.pdf)

**Comment by Nixx-K** [comment]
Dziękuję bardzo!

czw., 14 lis 2024, 01:46 użytkownik ikmmm ***@***.***>
napisał:
