### ISSUE TITLE
Zaprojektować resztę designu strony

### ISSUE THREAD

**Issue by Nixx-K** [IO-Lab2/Front-end#2]
WAŻNE - jednak nie scrapujemy rodzaju publikacji, więc możecie pozbyć się filtra odpowiadającego.

Stwórzcie dwa warianty: do stron, na których użytkownik może wybrać uczelnię oraz dyscyplinę, dodajcie przycisk "Dalej". Po dwukrotnym wybraniu przycisku przechodzimy do wyszukiwarki naukowców. W przypadku wybrania uczelni lub dyscypliny, po przejściu do wyszukiwarki naukowców mamy rozwinięty pasek filtrów i widzimy, że wybrana wcześniej uczelnia lub dyscyplina jest już zaznaczona. Zaprojektujcie również resztę wyszukiwarki, czyli widoczne po prawej stronie od paska filtrów profile naukowców pasujących do wyszukiwania. Takie profile mają mieć widoczne imię, nazwisko, tytuł/stanowisko, Instytut oraz Katedrę. 

Po wejściu w profil naukowca chcę mieć wyznaczone miejsce na id naukowca, imię i nazwisko, stanowisko, mail, URL do profilu w bazie danych uczelni, liczbę punktów ministerialnych, współczynnik Impact Factor (IF), h-indexy WoS oraz Scopus, nazwy dyscyplin, którymi się zajmuje (oraz liczbę procent zaangażowania, jeżeli dyscyplin jest więcej niż jedna), punkty ministerialne, współczynnik IF. 
Ma być tam również osobna zakładka z organizacjami i kolejna z publikacjami. W zakładce z publikacjami  chciałabym zobaczyć nazwę publikacji, jej datę, czasopismo, a pod spodem wylistowanych wszystkich jej autorów.

Na dole po prawej ma się pojawić przycisk "Porównaj z...", po wybraniu którego przechodzimy po raz kolejny do wyszukiwarki naukowców (z taką różnicą, że na górze napisane "Porównaj [insert tytuł, imię i nazwisko] z...". Ma się dać wybrać do 9 dodatkowych naukowców, z dowolnej uczelni i dyscypliny. Po wyborze osoby, chcemy wyświetlić na przepołowionej stronie (w przypadku parzystej liczby naukowców):
z lewej - wybranego uprzednio naukowca, jego tytuł, imię i nazwisko, oraz id. Pod spodem instytut, Katedrę oraz uczelnię. Na samym dole ma się znajdować współczynnik IF, punkty ministerialne i liczba publikacji.
z prawej - to samo, ale dla nowego naukowca. Jeżeli naukowców jest więcej niż 2, zróbmy kilka wierszy, czyli po prostu porównujemy kolejne dwa profile obok siebie pod dwoma wcześniejszymi.
Jeśli naukowców jest nieparzysta ilość, jeden naukowiec będzie bez graficznej pary, czyli wyświetlamy jego profil pod wcześniejszymi profilami na lewej połowie strony. Po prawej nie ma nic.

Na samym dole ma się znaleźć podsumowanie, czyli wykresy kołowe dla : 1. IF, 2. punktów ministerialnych, 3. liczby publikacji. Po najechaniu na jedną z dwóch części wykresu chcemy wyświetlić ilość (odpowiednio IF, punktów ministerialnych oraz liczby publikacji) wraz z tytułem, imieniem i nazwiskiem naukowca, do którego należy dana część wykresu.

Chciałabym zobaczyć również jasny wariant strony (wystarczy jeden, np. do wyszukiwarki naukowców).

**Comment by Nixx-K** [comment]
@ChrupiacePikle @Cryosmium Proszę o informację, z którego frameworka będziecie korzystać przy pracy - React czy Angular.

**Comment by Cryosmium** [comment]
> Proszę o informację, z którego frameworka będziecie korzystać przy pracy - React czy Angular.

Zdecydowaliśmy się używać Reacta.

Oryginalnie planowaliśmy użyć do niego języka TypeScript, ale wolę tu usłyszeć potwierdzenie od @ChrupiacePikle czy dalej tak jest, i czy nie woli on jednak pracować w zwykłym JavaScripcie.

**Comment by Nixx-K** [comment]
Dziękuję za info!

**Comment by ChrupiacePikle** [comment]
Jak tu sie pisze

**Comment by ChrupiacePikle** [comment]
O dobra, no tak typescript wybraliśmy

**Comment by Nixx-K** [comment]
@ikmmm Na czym stoicie na ten moment?

**Comment by Cryosmium** [comment]
Nie wiem jak inni, więc ja tylko podsumuję jaki progress jest od mojej strony.
Głównie ostatni tydzień spędziłem nauką Reacta na małym, testowym projekcie (w React + Vite). Obecnie, jestem już gotów w każdym momencie wygenerować nową konfigurację Reacta i rozpocząć pracę nad kodem.

**Comment by ikmmm** [comment]
Hej,
Ja w tym tygodniu do swojego projektu designu dodałem na razie:
- wspomniane na zajęciach przyciski "pomiń" przy ekranach wyborów
- widok przefiltrowanych naukowców z tytułem naukowym, imieniem i nazwiskiem, katedrą i instytutem
- dodałem dodatkowo przycisk "sortuj według", może się przydać

Generalnie ten przycisk ciemnego/jasnego motywu miał początkowo służyć do przełączania się w tryb "wysoki kontrast", bo tak jest na stronie bazy wiedzy SGGW - w załączonym pliku na ostatnim slajdzie jest prowizoryczny pomysł tego jak by to mogło wyglądać, ale w sumie nie wiem czy musimy to wstawiać. Możecie dać znać czy warto ewentualnie kombinować z tym jasnym/ciemnym motywem, czy może lepiej zająć się innymi rzeczami

Nie ukrywam że chciałem zrobić trochę więcej w tym tygodniu, ale trochę mnie przygniotły różne obowiązaki noooo i wyszło jak wyszło, dlatego wysyłam to tu teraz o 1 w nocy xd
Ale od piątku raczej będę już mógł się porządnie zająć resztą zadań i myślę że niedługo będziemy mogli już normalnie ruszać z front-endem

[tutaj plik z update'ami](https://github.com/user-attachments/files/17838072/Baza.Wiedzy.pdf)

**Comment by Nixx-K** [comment]
@ikmmm Na razie nie trzeba kombinować z kontrastem, jeżeli zostanie nam czas to zajmiemy się tym na koniec. I skoro tak było na stronie bazy SGGW, zostawmy w planach na przyszłość kontrast, a nie jasny/ciemny tryb. Dzięki za info!

**Comment by Nixx-K** [comment]
@ikmmm Co miałeś na myśli przy sortowaniu poprzez relewantność?

**Comment by ikmmm** [comment]
@Nixx-K o co chodzi z zakładką z organizacjami? o jakie organizacje chodzi?

**Comment by Nixx-K** [comment]
@ikmmm Cześć, faktycznie niejasno to napisałam. Przez organizacje miałam na myśli dyscypliny i przypadkiem powieliłam to, co było już napisane. 

W takim razie rezygnujemy z zakładki i wpisujemy dyscypliny wraz z procentem zaangażowania razem ze wszystkimi innymi danymi. Osobna zakładka będzie do publikacji.

**Comment by ikmmm** [comment]
Hej, załączam zaktualizowaną wersję designu :)
Wydaje mi się, że zawarłem wszystko o czym była mowa, ale gdyby czegoś brakowało albo trzeba było coś zmienić/poprawić to dawajcie znać 👍 

[Baza Wiedzy (1).pdf](https://github.com/user-attachments/files/17940800/Baza.Wiedzy.1.pdf)

**Comment by ikmmm** [comment]
myślałem też o tym, żeby przy wyborze instytutu dać nad nazwami jakieś symboliczne ikonki (np. nad naukami biologicznymi dać liść itp) - jeśli byście chcieli to mogę przygotować coś takiego

**Comment by Nixx-K** [comment]
> myślałem też o tym, żeby przy wyborze instytutu dać nad nazwami jakieś symboliczne ikonki (np. nad naukami biologicznymi dać liść itp) - jeśli byście chcieli to mogę przygotować coś takiego

Co do tego dam Ci znać jutro, ale nie wydaje mi się, żeby było potrzebne. Poza tym design wygląda świetnie, jutro napiszę czy potrzebujemy jeszcze czegoś.

**Comment by Nixx-K** [comment]
Design uznaliśmy za gotowy, zamykam issue.
